try{
    hello();
} catch(error){
    console.log(error);
}

try{
    anoterFn();
} catch{
    console.log('Error en la linea 10');
}